export default [
  {
    title:"1 - Burn The Elastic",
    artist: "Dj - Kurtis el Khaleel",
    cover: "burn.jpg",
    file: "VioletBurnTheElastic.mp3",
  },  
  {
    title:"2 - Play It Again",
    artist: "Torsten Fenslau",
    cover: "out.jpg",
    file: "OutOfTheOrdinary-PlayItAgain.mp3",
  },  
  {
    title:"3 - Good Life Cj's Living Good",
    artist: "Kevin Saunderson",
    cover: "ineed.jpg",
    file: "InnerCity-GoodLife-(CJ'sLivingGoodClubMix).mp3",
  },  
  {
    title:"4 - The Freaks",
    artist: "Dj Deeon",
    cover: "freaks.jpg",
    file: "Deeon-TheFreaks.mp3",
  },  
  {
    title:"5 - Fever Express",
    artist: "George Acosta",
    cover: "fever.jfif",
    file: "GeorgeAcosta-Fever.mp3",
  },  
  {
    title:"6 - Destination Unknown",
    artist: "Green Velvet",
    cover: "velv.jpg",
    file: "GreenVelvet-DestinationUnknown.mp3",
  },  
  {
    title:"7 - No Matter What I Do It's All About You Rock Da Planet",
    artist: "Alexia",
    cover: "hipo.jpg",
    file: "Alexia-NoMatterWhatIDo[It'sAllAboutYou](RockDaPlanetMix).mp3",
  },
  {
    title:"8 - Schöneberg Moonmen Over Marmion",
    artist: "Marmion",
    cover: "hipo2.jpg",
    file: "Marmion-Schöneberg(MoonmenOverMarmionRemix).mp3",
  },
  {
    title:"9 - Jack The Beat",
    artist: "Jeff Mills",
    cover: "hipo3.jpg",
    file: "WickedWipeJackTheBeatOriginal.mp3",
  },
  {
    title:"10 - Breakdown",
    artist: "Dj Self & Dj Trajic",
    cover: "djselfdjtrajic.jpg",
    file: "Self&TrajicBreakdownMix.mp3",
  },
  {
    title:"11 - Jack The Beat",
    artist: "Wicked Wipe",
    cover: "hipo4.jpg",
    file: "WickedWipe-JackTheBeatRemix.mp3",
  },
  {
    title:"12 - To The Three",
    artist: "Eric Vidal & Nick Vidal",
    cover: "phoenix.jpg",
    file: "SP1200-ToTheThree.mp3",
  },
  {
    title:"13 - I'm Gonna Love You",
    artist: "Summer Junkies",
    cover: "phoenix2.jpg",
    file: "SummerJunkiesIm.mp3",
  },
  {
    title:"14 - Bass Planet Beats",
    artist: "Summer Junkies",
    cover: "planetbass.jpg",
    file: "BassPlanetBeats.mp3",
  },
  {
    title:"15 - Witch Doktor Dark Ages",
    artist: "Armand Van Helden ",
    cover: "doktor.jpg",
    file: "ArmandVanHeldenWitchDoktorDarkAgesMix.mp3",
  },  
  {
    title:"16 - Too Nice To Be Real",
    artist: "T 99",
    cover: "t99.jpg",
    file: "T99-TooNiceToBeReal.mp3",
  },  
  {
    title:"17 - Godfather Freestyle",
    artist: "Christos Kemanetzidis",
    cover: "godf.jpg",
    file: "BlackPoweGodfatherFreestylePartyMix.mp3",
  },  
  {
    title:"18 - Mothership Reconnection Daft Punk",
    artist: "Scott Grooves Feat. Parliament Funkadelic",
    cover: "scoot.jpg",
    file: "ScottGroovesMothershipDaftPunkRemix.mp3",
  }, 
  {
    title:"19 - Waves Of Life",
    artist: "The Mover - Dj Alberto",
    cover: "alberto.jpg",
    file: "TheMoverWavesOfLifeDJAlbertoRemix.mp3",
  },   
  {
    title:"20 - Rollerblade Club",
    artist: "Georg O. Luksch",
    cover: "movin.jfif",
    file: "Movin'Melodies-Rollerblade(Club69FutureMix).mp3",
  },    
  {
    title:"21 - The Buddha Monks Funky Fresh",
    artist: "Dj Stew Featuring ",
    cover: "move.jpg",
    file: "DJStewBMonks-FF.mp3",
  },    
  {
    title:"22 - The Friction Remix",
    artist: "Dj Trajic",
    cover: "friction.jfif",
    file: "DjTrajic-TheFriction.mp3",
  },    
  {
    title:"23 - Beachball",
    artist: "Nalin & Kane, Dj Icey's",
    cover: "nalin.jfif",
    file: "Nalin&Kane-Beachball(DJIcey'sBassMix).mp3",
  },    
  {
    title:"24 - Bombscare",
    artist: "2 Bad Mice",
    cover: "boombscare.jfif",
    file: "Bombscare.mp3",
  },    
  {
    title:"25 - Hocus Pocus",
    artist: "Dj Irene",
    cover: "hocus.jpg",
    file: "HocusPocus.mp3",
  },    
  {
    title:"26 - Don't Go",
    artist: "Awesome 3",
    cover: "dont.jpg",
    file: "DontGoAwsome.mp3",
  },    
  {
    title:"27 - Shake It",
    artist: "Gary Martin",
    cover: "shake.jpg",
    file: "GigiGalaxy-ShakeIt.mp3",
  },    
  {
    title:"28 - Pony",
    artist: "Genwine",
    cover: "pony.jpg",
    file: "Genwine-Pony(MIAMI)BRNDance.mp3",
  },    
  {
    title:"29 - Meet Her At The Love Parade",
    artist: "Da Hool",
    cover: "hool.jfif",
    file: "DaHool-MeetLove.mp3",
  },    
  {
    title:"30 - Summertime Summertime",
    artist: "Corina",
    cover: "corina.jpg",
    file: "Corina-SummertimeSummertime1997.mp3",
  },     
  {
    title:"31 - Plastic Dreams",
    artist: "Jaydee",
    cover: "jaydee.jfif",
    file: "Jaydee-PlasticDreamsHQ(OriginalLongVersion).mp3",
  },     
  {
    title:"32 - Friction",
    artist: "Dj Trajic",
    cover: "friction.jfif",
    file: "DJTrajicFriction.mp3",
  },     
  {
    title:"33 - Get Freaky",
    artist: "Flying Steps",
    cover: "freak.jfif",
    file: "MusicInstructorfeat.mp3",
  },     
  {
    title:"34 - I Can See",
    artist: "SF Spanish Fly",
    cover: "cansee.jfif",
    file: "SFSpanishFly-Icansee(Haus-a-holicsmixv2).mp3",
  },     
  {
    title:"35 - Feel It",
    artist: "Todd Terry",
    cover: "feel.jpg",
    file: "Blurr-FeelIt.mp3",
  },       
  {
    title:"36 - Set U Free",
    artist: "Planet Soul",
    cover: "setyou.jpg",
    file: "SetUFree.mp3",
  },       
  {
    title:"37 - A Little Bit of Ecstasy",
    artist: " Jocelyn Enriquez",
    cover: "joce.jpg",
    file: "Little.mp3",
  },     
  {
    title:"38 - Turn Me Out",
    artist: "Kathy Brown",
    cover: "kathy.jpg",
    file: "kathBrownTurnMeOut.mp3",
  },     
  {
    title:"39 - Set It Off ",
    artist: "Strafe",
    cover: "set.jpg",
    file: "SetItOff.mp3",
  },     
  {
    title:"40 - Egypt, Egypt",
    artist: "The Egyptian Lover",
    cover: "egypt.jfif",
    file: "TheEgyptian.mp3",
  },     
  {
    title:"41 - Higher State of Consciousness",
    artist: "Josh Wink",
    cover: "josh.jpg",
    file: "JoshWink-HigherState.mp3",
  },     
  {
    title:"42 - We Do It Like This",
    artist: "Dj Icey",
    cover: "ice.jfif",
    file: "djicey-wedoitlikethis.mp3",
  },    
  {
    title:"43 - Rock the Beet",
    artist: "Dj Trajic",
    cover: "traj.jpg",
    file: "Rock.mp3",
  },    
  {
    title:"44 - Rock The Funky Beats",
    artist: "Natural Born Chillers",
    cover: "natu.jpg",
    file: "Natural.mp3",
  },    
  {
    title:"45 - This Is Los Angeles",
    artist: "Mark V. & Poogie Bear",
    cover: "mark.jpg",
    file: "This.mp3",
  },    
  {
    title:"46 - Pants R Saggin' ",
    artist: "Dj Trajic",
    cover: "pant.jpg",
    file: "Pant.mp3",
  }, 
  {
    title:"47 - The Party Has Begun",
    artist: "FreeStyle",
    cover: "the.jpg",
    file: "The.mp3",
  }, 
  {
    title:"48 - Don't Stop The Rock",
    artist: "FreeStyle",
    cover: "free.jpg",
    file: "FreeStyleDontStopTheRock.mp3",
  },  
  {
    title:"49 - When I Hear Music",
    artist: "Debbie Deb",
    cover: "wheni.jpg",
    file: "WhenIHearMusic.mp3",
  },  
  {
    title:"50 - They're Playing Our Song",
    artist: "Trinere",
    cover: "trinere.jpg",
    file: "TheyrePlayingOurSong.mp3",
  }, 
  {
    title:"51 - Look Out Weekend",
    artist: "Debbie Deb",
    cover: "lookout.jpg",
    file: "LookoutWeekend.mp3",
  }, 
  {
    title:"52 - Funky Little Beat",
    artist: "Connie",
    cover: "connie.jpg",
    file: "connie.mp3",
  },   
  {
    title:"53 - Take Me In Your Arms",
    artist: "Lil Suzy",
    cover: "lil.jpg",
    file: "LilSuzyTakeMeInYourArms.mp3",
  },   
  {
    title:"54 - In A Dream",
    artist: "Rockell",
    cover: "inadream.jpg",
    file: "InADream.mp3",
  },    
  {
    title:"55 - So, Tell Me, Tell Me",
    artist: "Shavonne",
    cover: "so.jpg",
    file: "SoTellMeTellMe.mp3",
  },     
  {
    title:"56 - Say It's Gonna Rain",
    artist: "Will to Power",
    cover: "will.jpg",
    file: "Say.mp3",
  },     
  {
    title:"57 - Play at Your Own Risk",
    artist: "Planet Patrol",
    cover: "playat.jpg",
    file: "PlayatYourOwnRisk.mp3",
  },     
  {
    title:"58 - Freak It",
    artist: "Lathun Grady",
    cover: "lathun.jpg",
    file: "LathunGradyFreakIt.mp3",
  },     
  {
    title:"59 - Jam On It",
    artist: "Newcleus",
    cover: "jam.jpg",
    file: "JamOnIt.mp3",
  },      
  {
    title:"60 - Just Like the Windt",
    artist: "Tony Garcia",
    cover: "just.jpg",
    file: "JustLiketheWind.mp3",
  },      
  {
    title:"61 - Let the Music Play",
    artist: "Shannon",
    cover: "letmusic.jpg",
    file: "LettheMusicPlay.mp3",
  },       
  {
    title:"62 - It Takes Two",
    artist: "Rob Base & DJ EZ Rock",
    cover: "rob.jpg",
    file: "ItTakesTwo.mp3",
  },       
  {
    title:"63 - Children's Story",
    artist: "Slick Rick",
    cover: "slick.jpg",
    file: "ChildrenStory.mp3",
  },      
  {
    title:"64 - This Is How We Do It",
    artist: "Montell Jordan",
    cover: "this.jpg",
    file: "ThisIsHowWeDoIt.mp3",
  },      
  {
    title:"65 - Push It",
    artist: "Salt-N-Pepa",
    cover: "push.jpg",
    file: "PushIt.mp3",
  },     
  {
    title:"66 - Supersonic",
    artist: "J. J. Fad (Juana, Juanita, Fatima, Anna, and Dana)",
    cover: "sonic.jpg",
    file: "Supersonic.mp3",
  },  
];


