export default [
  {
    title:"1 - Burn The Elastic - Abertura",
    artist: "Violet",
    cover: "burn.jpg",
    file: "VioletBurnTheElastic.mp3",
  },  
  {
    title:"2 - Play It Again",
    artist: "Out Of The Ordinary",
    cover: "out.jpg",
    file: "OutOfTheOrdinary-PlayItAgain.mp3",
  },  
  {
    title:"3 - Good Life CJ's Living Good Club Mix)",
    artist: "Inner City",
    cover: "ineed.jpg",
    file: "InnerCity-GoodLife-(CJ'sLivingGoodClubMix).mp3",
  },  
  {
    title:"4 - The Freaks",
    artist: "DJ Deeon",
    cover: "freaks.jpg",
    file: "Deeon-TheFreaks.mp3",
  },  
  {
    title:"5 - Fever Express",
    artist: "George Acosta",
    cover: "fever.jfif",
    file: "GeorgeAcosta-FeverExpress(100%VocalFever).mp3",
  },  
  {
    title:"6 - Destination Unknown",
    artist: "Green Velvet",
    cover: "velv.jpg",
    file: "GreenVelvet-DestinationUnknown.mp3",
  },  
  {
    title:"7 - No Matter What I Do It's All About You Rock Da Planet Mix",
    artist: "Alexia",
    cover: "hipo.jpg",
    file: "Alexia-NoMatterWhatIDo[It'sAllAboutYou](RockDaPlanetMix).mp3",
  },
  {
    title:"8 - Schöneberg Moonmen Over Marmion Remix",
    artist: "Marmion",
    cover: "hipo2.jpg",
    file: "Marmion-Schöneberg(MoonmenOverMarmionRemix).mp3",
  },
  {
    title:"9 - Jack The Beat Original",
    artist: "Wicked Wipe",
    cover: "hipo3.jpg",
    file: "WickedWipeJackTheBeatOriginal.mp3",
  },
  {
    title:"10 - Breakdown Mix",
    artist: "Dj Self & Dj Trajic",
    cover: "djselfdjtrajic.jpg",
    file: "Self&TrajicBreakdownMix.mp3",
  },
  {
    title:"11 - Jack The Beat Remix",
    artist: "Wicked Wipe",
    cover: "hipo4.jpg",
    file: "WickedWipe-JackTheBeatRemix.mp3",
  },
  {
    title:"12 - To The Three Original Mix",
    artist: "SP 1200",
    cover: "phoenix.jpg",
    file: "SP1200-ToTheThree.mp3",
  },
  {
    title:"13 - I'm Gonna Love You",
    artist: "Summer Junkies",
    cover: "phoenix2.jpg",
    file: "SummerJunkiesIm.mp3",
  },
  {
    title:"14 - Bass Planet Beats",
    artist: "Summer Junkies",
    cover: "planetbass.jpg",
    file: "BassPlanetBeats.mp3",
  },
  {
    title:"15 - Witch Doktor Dark Ages Mix",
    artist: "Armand Van Helden ",
    cover: "doktor.jpg",
    file: "ArmandVanHeldenWitchDoktorDarkAgesMix.mp3",
  },  
  {
    title:"16 - Too Nice To Be Real",
    artist: "T 99",
    cover: "t99.jpg",
    file: "T99-TooNiceToBeReal.mp3",
  },  
  {
    title:"17 - Godfather Freestyle Party Mix",
    artist: "Black Power",
    cover: "godf.jpg",
    file: "BlackPoweGodfatherFreestylePartyMix.mp3",
  },  
  {
    title:"18 - Mothership Reconnection Daft Punk Remix",
    artist: "Scott Grooves Feat. Parliament Funkadelic",
    cover: "scoot.jpg",
    file: "ScottGroovesMothershipDaftPunkRemix.mp3",
  }, 
  {
    title:"19 - Waves Of Life '97 Remix",
    artist: "The Mover - DJ Alberto",
    cover: "alberto.jpg",
    file: "TheMoverWavesOfLifeDJAlbertoRemix.mp3",
  },   
  {
    title:"20 - Rollerblade Club 69 Future Mix",
    artist: "Movin'Melodies",
    cover: "move.jpg",
    file: "Movin'Melodies-Rollerblade(Club69FutureMix).mp3",
  },  
];
