export default [
  {
    title:"1 - Burn The Elastic",
    artist: "Violet",
    cover: "burn.jpg",
    file: "VioletBurnTheElastic.mp3",
  },  
  {
    title:"2 - Play It Again",
    artist: "Out Of The Ordinary",
    cover: "out.jpg",
    file: "OutOfTheOrdinary-PlayItAgain.mp3",
  },  
  {
    title:"3 - Good Life Cj's Living Good",
    artist: "Inner City",
    cover: "ineed.jpg",
    file: "InnerCity-GoodLife-(CJ'sLivingGoodClubMix).mp3",
  },  
  {
    title:"4 - The Freaks",
    artist: "Dj Deeon",
    cover: "freaks.jpg",
    file: "Deeon-TheFreaks.mp3",
  },  
  {
    title:"5 - Fever Express",
    artist: "George Acosta",
    cover: "fever.jfif",
    file: "GeorgeAcosta-Fever.mp3",
  },  
  {
    title:"6 - Destination Unknown",
    artist: "Green Velvet",
    cover: "velv.jpg",
    file: "GreenVelvet-DestinationUnknown.mp3",
  },  
  {
    title:"7 - No Matter What I Do It's All About You Rock Da Planet",
    artist: "Alexia",
    cover: "hipo.jpg",
    file: "Alexia-NoMatterWhatIDo[It'sAllAboutYou](RockDaPlanetMix).mp3",
  },
  {
    title:"8 - Schöneberg Moonmen Over Marmion",
    artist: "Marmion",
    cover: "hipo2.jpg",
    file: "Marmion-Schöneberg(MoonmenOverMarmionRemix).mp3",
  },
  {
    title:"9 - Jack The Beat",
    artist: "Wicked Wipe",
    cover: "hipo3.jpg",
    file: "WickedWipeJackTheBeatOriginal.mp3",
  },
  {
    title:"10 - Breakdown",
    artist: "Dj Self & Dj Trajic",
    cover: "djselfdjtrajic.jpg",
    file: "Self&TrajicBreakdownMix.mp3",
  },
  {
    title:"11 - Jack The Beat",
    artist: "Wicked Wipe",
    cover: "hipo4.jpg",
    file: "WickedWipe-JackTheBeatRemix.mp3",
  },
  {
    title:"12 - To The Three",
    artist: "SP 1200",
    cover: "phoenix.jpg",
    file: "SP1200-ToTheThree.mp3",
  },
  {
    title:"13 - I'm Gonna Love You",
    artist: "Summer Junkies",
    cover: "phoenix2.jpg",
    file: "SummerJunkiesIm.mp3",
  },
  {
    title:"14 - Bass Planet Beats",
    artist: "Summer Junkies",
    cover: "planetbass.jpg",
    file: "BassPlanetBeats.mp3",
  },
  {
    title:"15 - Witch Doktor Dark Ages",
    artist: "Armand Van Helden ",
    cover: "doktor.jpg",
    file: "ArmandVanHeldenWitchDoktorDarkAgesMix.mp3",
  },  
  {
    title:"16 - Too Nice To Be Real",
    artist: "T 99",
    cover: "t99.jpg",
    file: "T99-TooNiceToBeReal.mp3",
  },  
  {
    title:"17 - Godfather Freestyle",
    artist: "Black Power",
    cover: "godf.jpg",
    file: "BlackPoweGodfatherFreestylePartyMix.mp3",
  },  
  {
    title:"18 - Mothership Reconnection Daft Punk",
    artist: "Scott Grooves Feat. Parliament Funkadelic",
    cover: "scoot.jpg",
    file: "ScottGroovesMothershipDaftPunkRemix.mp3",
  }, 
  {
    title:"19 - Waves Of Life",
    artist: "The Mover - Dj Alberto",
    cover: "alberto.jpg",
    file: "TheMoverWavesOfLifeDJAlbertoRemix.mp3",
  },   
  {
    title:"20 - Rollerblade Club",
    artist: "Movin' Melodies",
    cover: "movin.jfif",
    file: "Movin'Melodies-Rollerblade(Club69FutureMix).mp3",
  },    
  {
    title:"21 - The Buddha Monks Funky Fresh",
    artist: "Dj Stew Featuring ",
    cover: "move.jpg",
    file: "DJStewBMonks-FF.mp3",
  },    
  {
    title:"22 - The Friction Remix",
    artist: "Dj Trajic",
    cover: "friction.jfif",
    file: "DjTrajic-TheFriction.mp3",
  },    
  {
    title:"23 - Beachball",
    artist: "Nalin & Kane, Dj Icey's",
    cover: "nalin.jfif",
    file: "Nalin&Kane-Beachball(DJIcey'sBassMix).mp3",
  },    
  {
    title:"24 - Bombscare",
    artist: "2 Bad Mice",
    cover: "boombscare.jfif",
    file: "Bombscare.mp3",
  },    
  {
    title:"25 - Hocus Pocus",
    artist: "Dj Irene",
    cover: "hocus.jpg",
    file: "HocusPocus.mp3",
  },    
  {
    title:"26 - Don't Go",
    artist: "Awesome 3",
    cover: "dont.jpg",
    file: "DontGoAwsome.mp3",
  },    
  {
    title:"27 - Shake It",
    artist: "Gigi Galaxy",
    cover: "shake.jpg",
    file: "GigiGalaxy-ShakeIt.mp3",
  },    
  {
    title:"28 - Pony",
    artist: "Genwine",
    cover: "pony.jpg",
    file: "Genwine-Pony(MIAMI)BRNDance.mp3",
  },    
  {
    title:"29 - Meet Her At The Love Parade",
    artist: "Da Hool",
    cover: "hool.jfif",
    file: "DaHool-MeetLove.mp3",
  },    
  {
    title:"30 - Summertime Summertime",
    artist: "Corina",
    cover: "corina.jpg",
    file: "Corina-SummertimeSummertime1997.mp3",
  },     
  {
    title:"31 - Plastic Dreams",
    artist: "Jaydee",
    cover: "jaydee.jfif",
    file: "Jaydee-PlasticDreamsHQ(OriginalLongVersion).mp3",
  },     
  {
    title:"32 - Friction",
    artist: "Dj Trajic",
    cover: "friction.jfif",
    file: "DJTrajicFriction.mp3",
  },     
  {
    title:"33 - Get Freaky",
    artist: "Flying Steps",
    cover: "freak.jfif",
    file: "MusicInstructorfeat.mp3",
  },     
  {
    title:"34 - I Can See",
    artist: "SF Spanish Fly",
    cover: "cansee.jfif",
    file: "SFSpanishFly-Icansee(Haus-a-holicsmixv2).mp3",
  },     
  {
    title:"35 - Feel It",
    artist: "Blurr",
    cover: "feel.jpg",
    file: "Blurr-FeelIt.mp3",
  },     
  {
    title:"36 - Turn Me Out",
    artist: "Kath Brown",
    cover: "hipo.jpg",
    file: "kathBrownTurnMeOut.mp3",
  },     
  {
    title:"37 - Set It Off ",
    artist: "Strafe",
    cover: "set.jpg",
    file: "SetItOff.mp3",
  },     
  {
    title:"38 - Egypt, Egypt",
    artist: "The Egyptian Lover",
    cover: "egypt.jfif",
    file: "TheEgyptian.mp3",
  },     
  {
    title:"39 - Higher State of Consciousness",
    artist: "Josh Wink",
    cover: "josh.jpg",
    file: "JoshWink-HigherState.mp3",
  },     
  {
    title:"40 - We Do It Like This",
    artist: "Dj Icey",
    cover: "ice.jfif",
    file: "djicey-wedoitlikethis.mp3",
  }, 
  {
    title:"41 - Don't Stop The Rock",
    artist: "FreeStyle",
    cover: "free.jpg",
    file: "FreeStyleDontStopTheRock.mp3",
  },  
  {
    title:"42 - When I Hear Music",
    artist: "Debbie Deb",
    cover: "wheni.jpg",
    file: "WhenIHearMusic.mp3",
  }, 
  {
    title:"43 - Look Out Weekend",
    artist: "Debbie Deb",
    cover: "lookout.jpg",
    file: "LookoutWeekend.mp3",
  }, 
  {
    title:"44 - Funky Little Beat",
    artist: "Connie",
    cover: "connie.jpg",
    file: "connie.mp3",
  },   
  {
    title:"45 - Take Me In Your Arms",
    artist: "Lil Suzy",
    cover: "lil.jpg",
    file: "LilSuzyTakeMeInYourArms.mp3",
  },   
  {
    title:"46 - In A Dream",
    artist: "Rockell",
    cover: "inadream.jpg",
    file: "InADream.mp3",
  },    
  {
    title:"47 - So, Tell Me, Tell Me",
    artist: "Shavonne",
    cover: "so.jpg",
    file: "SoTellMeTellMe.mp3",
  },  
];


